version: 0.0
os: linux
files:
  - source: ./requirements.txt
    destination: /tmp
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root
