version: 0.0
os: linux
files:
  - source: /
    destination: /usr/src/app
hooks:
  BeforeInstall:
    - location: pip install --no-cache-dir -r requirements.txt
      timeout: 300
      runas: root

  ApplicationStart:
    - location: cd /usr/src/app && gunicorn -c gunicorn_config.py flask-example:app 
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
